version: '3'

volumes:
  database:

services:
  database:
    image: mysql:8
    environment:
      MYSQL_DATABASE: budget
      MYSQL_USER: budget
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - database:/var/lib/mysql

  budget:
    build: .
    environment:
      DB_HOST: database
      DB_DATABASE: budget
      DB_USERNAME: budget
      DB_PASSWORD: test
